"""
Nifty 200 NSE tickers (Nifty 100 + Nifty Midcap 100).
Update periodically from NSE India website.
"""

# Nifty 100 tickers
NIFTY100_TICKERS = [
    "ABB", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ADANIENSOL", "AMBUJACEM",
    "APOLLOHOSP", "ASIANPAINT", "ATGL", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJAJHLDNG",
    "BAJFINANCE", "BANKBARODA", "BEL", "BERGEPAINT", "BHARTIARTL", "BOSCHLTD", "BPCL",
    "BRITANNIA", "CANBK", "CHOLAFIN", "CIPLA", "COALINDIA", "COLPAL", "DABUR", "DIVISLAB",
    "DLF", "DMART", "DRREDDY", "EICHERMOT", "GAIL", "GODREJCP", "GRASIM", "HAL", "HAVELLS",
    "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK",
    "ICICIGI", "ICICIPRULI", "INDIGO", "INDUSINDBK", "INFY", "IOC", "IRFC", "IRCTC", "ITC",
    "JINDALSTEL", "JIOFIN", "JSWSTEEL", "KOTAKBANK", "LICI", "LT", "LTIM", "M&M", "MARICO",
    "MARUTI", "MOTHERSON", "NAUKRI", "NESTLEIND", "NTPC", "ONGC", "PIDILITIND", "PNB",
    "POWERGRID", "PFC", "RECLTD", "RELIANCE", "SBICARD", "SBILIFE", "SBIN", "SHREECEM",
    "SHRIRAMFIN", "SIEMENS", "SRF", "SUNPHARMA", "TATACONSUM", "TATAMOTORS", "TATASTEEL",
    "TATAPOWER", "TCS", "TECHM", "TITAN", "TORNTPHARM", "TRENT", "TVSMOTOR", "ULTRACEMCO",
    "UNITDSPR", "VBL", "VEDL", "WIPRO", "ZYDUSLIFE", "ZOMATO",
]

# Nifty Midcap 100 tickers
NIFTYMIDCAP100_TICKERS = [
    "3MINDIA", "AARTIIND", "ABBOTINDIA", "ACE", "ADANIWILMAR", "AEGISLOG", "AIAENG", "AJANTPHARM",
    "ALKEM", "AMARAJABAT", "ANURAS", "APARINDS", "APLAPOLLO", "APOLLOTYRE", "ASHOKLEY", "ASTRAL",
    "ATUL", "AUBANK", "AUROPHARMA", "BALKRISIND", "BALRAMCHIN", "BANDHANBNK", "BATAINDIA",
    "BAYERCROP", "BDL", "BHARATFORG", "BHEL", "BLUEDART", "BLUESTARCO", "BRIGADE", "BSOFT",
    "CAMS", "CANFINHOME", "CARBORUNIV", "CASTROLIND", "CEATLTD", "CENTRALBK", "CENTURYPLY",
    "CESC", "CGPOWER", "CHALET", "CHAMBLFERT", "CLEAN", "COCHINSHIP", "COFORGE", "CONCOR",
    "COROMANDEL", "CREDITACC", "CROMPTON", "CUB", "CUMMINSIND", "CYIENT", "DALBHARAT",
    "DCBBANK", "DEEPAKNTR", "DELHIVERY", "DEVYANI", "DIXON", "EIDPARRY", "ELGIEQUIP", "EMAMILTD",
    "ENDURANCE", "ESCORTS", "EXIDEIND", "FEDERALBNK", "FACT", "FINEORG", "FSL", "GICRE",
    "GLAND", "GLAXO", "GLENMARK", "GMRINFRA", "GNFC", "GODFRYPHLP", "GODREJIND", "GODREJPROP",
    "GRANULES", "GRINDWELL", "GSPL", "GUJGASLTD", "HAPPSTMNDS", "HEG", "HFCL", "HINDCOPPER",
    "HINDPETRO", "HONAUT", "HUDCO", "IEX", "INDHOTEL", "INDIAMART", "INDIANB", "INDIGOPNTS",
    "IPCALAB", "JBCHEPHARM", "JINDALSAW", "JSL", "JUBLFOOD", "JUBLINGREA", "KAJARIACER",
    "KALYANKJIL", "KANSAINER", "KEI", "KIMS", "LALPATHLAB", "LAURUSLABS", "LICHSGFIN", "LINCOLN",
    "LTTS", "LUPIN", "M&MFIN", "MAHABANK", "MANAPPURAM", "MARATHON", "MAXHEALTH", "MAZDOCK",
    "MEDANTA", "METROBRAND", "MFSL", "MGL", "MIDHANI", "MOTILALOFS", "MPHASIS", "MRF",
    "NATCOPHARM", "NAVINFLUOR", "NBCC", "NCC", "NESCO", "NHPC", "NLCINDIA", "NMDC", "NSLNISP",
    "OBEROIRLTY", "OFSS", "OIL", "PAGEIND", "PATANJALI", "PAYTM", "PEL", "PERSISTENT",
    "PETRONET", "PFIZER", "PHOENIXLTD", "PIIND", "PNBHOUSING", "POLYCAB", "POONAWALLA",
    "PRESTIGE", "QUESS", "RADICO", "RAINBOW", "RAJESHEXPO", "RALLIS", "RATNAMANI", "RAYMOND",
    "RBLBANK", "RENUKA", "SANOFI", "SAPPHIRE", "SCHAEFFLER", "SFL", "SHARDAMOTR", "SHOPERSTOP",
    "SHYAMMETL", "SJVN", "SKFINDIA", "SOBHA", "SOLARINDS", "SONACOMS", "SRTRANSFIN", "STARHEALTH",
    "SUNDARMFIN", "SUNDRMFAST", "SUNTV", "SUPREMEIND", "SUVENPHAR", "SWANENERGY", "SYMPHONY",
    "SYNGENE", "TANLA", "TATACOMM", "TATAELXSI", "TATAINVEST", "TIINDIA", "TIMKEN", "TMB",
    "TRIDENT", "TTKPRESTIG", "TV18BRDCST", "UBL", "UCOBANK", "UNOMINDA", "UPL", "VAIBHAVGBL",
    "VOLTAS", "WHIRLPOOL", "WNS", "YESBANK", "ZEEL", "ZENSARTECH", "ZFCVINDIA", "ZOMATO",
]

# Combine and deduplicate
NIFTY200_TICKERS = sorted(set(NIFTY100_TICKERS + NIFTYMIDCAP100_TICKERS))[:200]
