"""
Nifty Midcap 100 + Nifty Smallcap 100 NSE tickers.
Update periodically from NSE India website.
"""

NIFTY_MIDCAP100_TICKERS = [
    "3MINDIA", "AARTIIND", "ABBOTINDIA", "ACE", "AEGISLOG", "AIAENG", "AJANTPHARM",
    "ALKEM", "ANURAS", "APARINDS", "APLAPOLLO", "APOLLOTYRE", "ASHOKLEY", "ASTRAL",
    "ATUL", "AUBANK", "AUROPHARMA", "BALKRISIND", "BALRAMCHIN", "BANDHANBNK", "BATAINDIA",
    "BAYERCROP", "BDL", "BHARATFORG", "BHEL", "BLUEDART", "BLUESTARCO", "BRIGADE", "BSOFT",
    "CAMS", "CANFINHOME", "CARBORUNIV", "CASTROLIND", "CEATLTD", "CENTRALBK", "CENTURYPLY",
    "CESC", "CGPOWER", "CHALET", "CHAMBLFERT", "CLEAN", "COCHINSHIP", "COFORGE", "CONCOR",
    "COROMANDEL", "CREDITACC", "CROMPTON", "CUB", "CUMMINSIND", "CYIENT", "DALBHARAT",
    "DCBBANK", "DEEPAKNTR", "DELHIVERY", "DEVYANI", "DIXON", "EIDPARRY", "ELGIEQUIP", "EMAMILTD",
    "ENDURANCE", "ESCORTS", "EXIDEIND", "FEDERALBNK", "FACT", "FINEORG", "FSL", "GICRE",
    "GLAND", "GLAXO", "GLENMARK", "GNFC", "GODFRYPHLP", "GODREJIND", "GODREJPROP",
    "GRANULES", "GRINDWELL", "GSPL", "GUJGASLTD", "HAPPSTMNDS", "HEG", "HFCL", "HINDCOPPER",
    "HINDPETRO", "HONAUT", "HUDCO", "IEX", "INDHOTEL", "INDIAMART", "INDIANB", "INDIGOPNTS",
    "IPCALAB", "JBCHEPHARM", "JINDALSAW", "JSL", "JUBLFOOD", "JUBLINGREA", "KAJARIACER",
    "KALYANKJIL", "KANSAINER", "KEI", "KIMS", "LALPATHLAB", "LAURUSLABS", "LICHSGFIN", "LINCOLN",
    "LTTS", "LUPIN", "M&MFIN", "MAHABANK", "MANAPPURAM", "MARATHON", "MAXHEALTH", "MAZDOCK",
    "MEDANTA", "METROBRAND", "MFSL", "MGL", "MIDHANI", "MOTILALOFS", "MPHASIS", "MRF",
    "NATCOPHARM", "NAVINFLUOR", "NBCC", "NCC", "NESCO", "NHPC", "NLCINDIA", "NMDC", "NSLNISP",
    "OBEROIRLTY", "OFSS", "OIL", "PAGEIND", "PATANJALI", "PEL", "PERSISTENT",
    "PETRONET", "PHOENIXLTD", "PIIND", "PNBHOUSING", "POLYCAB", "POONAWALLA",
    "PRESTIGE", "RADICO", "RAINBOW", "RATNAMANI", "RAYMOND",
    "RBLBANK", "RENUKA", "SAPPHIRE", "SCHAEFFLER", "SHARDAMOTR",
    "SJVN", "SKFINDIA", "SOBHA", "SOLARINDS", "SONACOMS", "SRTRANSFIN", "STARHEALTH",
    "SUNDARMFIN", "SUNDRMFAST", "SUNTV", "SUPREMEIND", "SUVENPHAR", "SYMPHONY",
    "SYNGENE", "TATACOMM", "TATAELXSI", "TATAINVEST", "TIINDIA", "TIMKEN",
    "TRIDENT", "TTKPRESTIG", "UBL", "UCOBANK", "UNOMINDA", "UPL", "VAIBHAVGBL",
    "VOLTAS", "WHIRLPOOL", "YESBANK", "ZEEL", "ZENSARTECH",
]

NIFTY_SMALLCAP100_TICKERS = [
    "AAVAS", "ALEMBICLTD", "ANANTRAJ", "ASTERDM", "BALAMINES",
    "BIKAJI", "CAPLIPOINT", "CARTRADE", "CDSL", "CRAFTSMAN",
    "DHANUKA", "EASEMYTRIP", "EMCURE", "EQUITASBNK", "ESABINDIA",
    "FINCABLES", "GOCOLORS", "GPIL", "HERITGFOOD", "HONASA",
    "INTELLECT", "IOLCP", "ISGEC", "JKLAKSHMI", "JKPAPER",
    "JMFINANCIL", "JYOTHYLAB", "KIRIINDS", "KNRCON", "KOLTEPATIL",
    "KRBL", "LATENTVIEW", "LAXMIMACH", "MANINFRA", "MASTEK",
    "MATRIMONY", "MANYAVAR", "METROPOLIS", "MINDACORP", "NAZARA",
    "NIACL", "NILKAMAL", "NOCIL", "NUVOCO", "ORIENTBELL",
    "ORIENTELEC", "PCBL", "POKARNA", "POLYMED", "PRAJIND",
    "RAMCOIND", "REDTAPE", "ROLEXRINGS", "ROUTE", "RPGLIFE",
    "SAFARI", "SENCO", "SHAKTIPUMP", "SPANDANA",
    "SSWL", "SUPRAJIT", "TATVA", "THYROCARE", "TNPL",
    "TRITURBINE", "TVSHLTD", "UJJIVANSFB", "UTIAMC", "VARDHMAN",
    "VSTIND", "WENDT", "CARERATING", "HLEGLAS", "GANDHAR",
    "IRCON", "SOLARA", "ABBEY", "JKCEMENT", "TANLA",
]

MIDSMALL_TICKERS = sorted(set(NIFTY_MIDCAP100_TICKERS + NIFTY_SMALLCAP100_TICKERS))
