"""
Nifty 100 NSE tickers (Nifty 50 + Nifty Next 50 style universe).
Update periodically from: https://www.niftyindices.com/IndexConstituent/ind_nifty100list.csv
"""

NIFTY100_TICKERS = [
    "ABB", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ADANIENSOL", "AMBUJACEM",
    "APOLLOHOSP", "ASIANPAINT", "ATGL", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJAJHLDNG",
    "BAJFINANCE", "BANKBARODA", "BEL", "BERGEPAINT", "BHARTIARTL", "BOSCHLTD", "BPCL",
    "BRITANNIA", "CANBK", "CHOLAFIN", "CIPLA", "COALINDIA", "COLPAL", "DABUR", "DIVISLAB",
    "DLF", "DMART", "DRREDDY", "EICHERMOT", "GAIL", "GODREJCP", "GRASIM", "HAL", "HAVELLS",
    "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK",
    "ICICIGI", "ICICIPRULI", "INDIGO", "INDUSINDBK", "INFY", "IOC", "IRFC", "IRCTC", "ITC",
    "JINDALSTEL", "JIOFIN", "JSWSTEEL", "KOTAKBANK", "LICI", "LT", "LTIM", "M&M", "MARICO",
    "MARUTI", "MOTHERSON", "NAUKRI", "NESTLEIND", "NTPC", "ONGC", "PIDILITIND", "PNB",
    "POWERGRID", "PFC", "RECLTD", "RELIANCE", "SBICARD", "SBILIFE", "SBIN", "SHREECEM",
    "SHRIRAMFIN", "SIEMENS", "SRF", "SUNPHARMA", "TATACONSUM", "TATAMOTORS", "TATASTEEL",
    "TATAPOWER", "TCS", "TECHM", "TITAN", "TORNTPHARM", "TRENT", "TVSMOTOR", "ULTRACEMCO",
    "UNITDSPR", "VBL", "VEDL", "WIPRO", "ZYDUSLIFE", "ZOMATO",
]

# Trim/pad to 100 unique symbols
NIFTY100_TICKERS = sorted(set(NIFTY100_TICKERS))[:100]
